Repository reactphp/async, pull requests merged in 2021-11, with the labels that each got.

#9 Support promise cancellation
  src/functions.php
  tests/ParallelTest.php
  tests/SeriesTest.php
  tests/WaterfallTest.php
Labels: new feature

#11 Require PHP 7.1+ and add type declarations
  .github/workflows/ci.yml
  README.md
  composer.json
  phpunit.xml.legacy
  src/functions.php
  tests/AwaitTest.php
  tests/TestCase.php
Labels: new feature, BC break

#12 Add Generator-based `coroutine()` function
  README.md
  src/functions.php
  tests/CoroutineTest.php
Labels: new feature

#13 Support promise cancellation for `coroutine()` and clean up garbage references
  src/functions.php
  tests/CoroutineTest.php
Labels: new feature

#14 Require PHP 8.1+ and add `mixed` type declarations
  .gitattributes
  .github/workflows/ci.yml
  README.md
  composer.json
  phpunit.xml.dist
  phpunit.xml.legacy
  src/functions.php
Labels: new feature, BC break

#15 Add Fiber-based `async` and `await` functions
  README.md
  composer.json
  src/FiberFactory.php
  src/FiberInterface.php
  src/SimpleFiber.php
  src/functions.php
  tests/AsyncTest.php
  tests/AwaitTest.php
Labels: new feature, BC break, maintenance
