Repository reactphp/async, pull requests merged in 2022-06, with the labels that each got.

#45 Support iterable type for `parallel()` + `series()` + `waterfall()`
  README.md
  src/functions.php
  tests/ParallelTest.php
  tests/SeriesTest.php
  tests/WaterfallTest.php
Labels: new feature

#55 [4.x] Consistent cancellation semantics for `async()` and `coroutine()`
  README.md
  composer.json
  src/FiberMap.php
  src/functions.php
  tests/AsyncTest.php
  tests/AwaitTest.php
  tests/CoroutineTest.php
Labels: new feature, BC break

#48 [4.x] Forward compatibility with upcoming Promise v3
  composer.json
  src/functions.php
  tests/SeriesTest.php
  tests/WaterfallTest.php
Labels: new feature, help wanted

#53 chore(docs): remove leading dollar sign
  README.md
Labels: maintenance

#52 chore(docs): remove leading dollar sign
  README.md
Labels: maintenance
